### ISSUE TITLE
Warp: Live Sync is out of sync

### ISSUE THREAD

**Issue by DaQuirm** [DaQuirm/css-quickdraw-redux#186]
😿

**Comment by DaQuirm** [comment]
```
Thu, 05 May 2016 21:45:16 GMT uncaughtException: Cannot read property 'solution' of undefined
TypeError: Cannot read property 'solution' of undefined
  at Entity.sync (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/common/entity.coffee:43:28)
  at Session.sync (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/server/session.coffee:49:17)
  at Service.sync (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/server/service.coffee:61:13)
  at WebSocketTransport.<anonymous> (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/server/service.coffee:35:49)
  at emitTwo (events.js:100:13)
  at WebSocketTransport.emit (events.js:185:7)
  at WebSocketTransport.onsync (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/server/transport/websocket-transport.coffee:48:4)
  at WebSocketServer.<anonymous> (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/server/transport/websocket-transport.coffee:33:5)
  at emitTwo (events.js:100:13)
  at WebSocketServer.emit (events.js:185:7)
  at WebSocketConnection.<anonymous> (/Users/daquirm/projects/css-quickdraw-redux/node_modules/nexus-warp/src/server/transport/websocket-server.coffee:20:6)
  at emitOne (events.js:90:13)
  at WebSocketConnection.emit (events.js:182:7)
  at WebSocketConnection.processFrame (/Users/daquirm/projects/css-quickdraw-redux/node_modules/websocket/lib/WebSocketConnection.js:547:26)
  at /Users/daquirm/projects/css-quickdraw-redux/node_modules/websocket/lib/WebSocketConnection.js:321:40
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by R1ZZU** [comment]
Sat, 07 May 2016 14:58:45 GMT uncaughtException: Cannot read property 'sync' of undefined
TypeError: Cannot read property 'sync' of undefined
  at Session.sync (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/src/server/session.coffee:49:16)
  at Service.sync (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/src/server/service.coffee:61:13)
  at WebSocketTransport.<anonymous> (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/src/server/service.coffee:35:49)
  at emitTwo (events.js:87:13)
  at WebSocketTransport.emit (events.js:172:7)
  at WebSocketTransport.onsync (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/src/server/transport/websocket-transport.coffee:48:4)
  at WebSocketServer.<anonymous> (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/src/server/transport/websocket-transport.coffee:33:5)
  at emitTwo (events.js:87:13)
  at WebSocketServer.emit (events.js:172:7)
  at WebSocketConnection.<anonymous> (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/src/server/transport/websocket-server.coffee:20:6)
  at emitOne (events.js:77:13)
  at WebSocketConnection.emit (events.js:169:7)
  at WebSocketConnection.processFrame (/Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/node_modules/websocket/lib/WebSocketConnection.js:547:26)
  at /Users/r1zzu/w/css-quickdraw-redux/node_modules/nexus-warp/node_modules/websocket/lib/WebSocketConnection.js:321:40
  at doNTCallback0 (node.js:417:9)
  at process._tickCallback (node.js:346:13)

**Comment by kirilknysh** [comment]
😭
