### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by kirilknysh** [DaQuirm/css-quickdraw-redux#226]
Wed, 11 May 2016 17:06:52 GMT uncaughtException: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
  at SessionManager.create (/var/www/cssqd/app/session-manager.coffee:18:55)
  at WebSocketServer.<anonymous> (/var/www/cssqd/node_modules/nexus-warp/src/server/transport/websocket-transport.coffee:19:29)
  at emitTwo (events.js:87:13)
  at WebSocketServer.emit (events.js:172:7)
  at WebSocketServer.<anonymous> (/var/www/cssqd/node_modules/nexus-warp/src/server/transport/websocket-server.coffee:17:5)
  at emitOne (events.js:77:13)
  at WebSocketServer.emit (events.js:169:7)
  at WebSocketServer.handleUpgrade (/var/www/cssqd/node_modules/nexus-warp/node_modules/websocket/lib/WebSocketServer.js:213:14)
  at emitThree (events.js:97:13)
  at Server.emit (events.js:175:7)
  at onParserExecuteCommon (_http_server.js:400:14)
  at HTTPParser.onParserExecute (_http_server.js:368:5)

**Comment by kirilknysh** [comment]
Protect nexus-warp socket connection?! (between server and client)
